name: CI
on:
  - push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        name: Setup Ruby
        with:
          ruby-version: 3.3.0
      - name: Lint
        run: |
          bundle install
          bin/rubocop
